// <auto-generated />
using System;
using AdPang.FileManager.EntityFrameworkCore.LogDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdPang.FileManager.EntityFrameworkCore.MigrationDb.LogDbMigration
{
    [DbContext(typeof(LogDbContext))]
    [Migration("20220709113904_InitLogDb")]
    partial class InitLogDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AdPang.FileManager.Models.LogEntities.ActionLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("OperaByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RequestIPAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestParameter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequsetUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ActionLog");
                });

            modelBuilder.Entity("AdPang.FileManager.Models.LogEntities.ExceptionLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExceptionMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OperaByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RequestIPAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestParameter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequsetUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExceptionLog");
                });
#pragma warning restore 612, 618
        }
    }
}
